### ISSUE TITLE
S_SHOW_ITEM_TOOLTIP

### ISSUE THREAD

**Issue by PinguinRei** [Tera-Shiraneko/item-id-finder#2]
[dispatch] handle: error running hook for S_SHOW_ITEM_TOOLTIP<10>
hook: (anonymous) in item id finder
data: { type: 20,

either there is an error or i need to catch the map?

**Comment by Tera-Shiraneko** [comment]
Which proxy are you using and do you use an datacenter mod?

**Comment by PinguinRei** [comment]
TERA Toolbox with some mods, datacenter mod i just heard

**Comment by Tera-Shiraneko** [comment]
Issue solved in discord dm.
